name: Main CI

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: Check TypeScript types
        run: npm run type-check

  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: quality-gates
    outputs:
      build-hash: ${{ steps.build-info.outputs.hash }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Generate build info
        id: build-info
        run: |
          BUILD_HASH=$(echo ${{ github.sha }} | cut -c1-8)
          echo "hash=$BUILD_HASH" >> "$GITHUB_OUTPUT"
          echo "Built from commit: ${{ github.sha }}" > .next/build-info.txt
          echo "Build time: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> .next/build-info.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ steps.build-info.outputs.hash }}
          path: .next/
          retention-days: 7

  basic-validation:
    name: Basic Validation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ needs.build.outputs.build-hash }}
          path: .next/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify build integrity
        run: |
          if [ ! -f ".next/build-info.txt" ]; then
            echo "❌ Build info not found"
            exit 1
          fi
          echo "✅ Build artifacts validation passed"
          cat .next/build-info.txt

      - name: Test API routes (unit)
        run: |
          # Quick validation that critical files exist
          if [ ! -f "src/app/api/health/route.ts" ]; then
            echo "❌ Health API route missing"
            exit 1
          fi
          echo "✅ API routes structure validated"

      - name: Security check
        run: npm audit --audit-level=high
